title: Michaels Random Texts
email: ---
description: >- # this means to ignore newlines until "baseurl:"
  Contains math, physics and c++ notes not seen at any other website.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://floppymike.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: "Michaellu"
  email: "---"
  url: "https://floppymike.github.io/"
permalink: /:year/:month/:day/:title:output_ext

favicon: "logo.png"
future: true

# Build settings
theme: jekyll-yamt

plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

paginate: 3
paginate_path: "/page:num/"

social:
  links: #List your social links here
    - https://www.github.com/floppyMike
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never